# Generated by Django 5.2.7 on 2025-10-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='finished',
        ),
    ]
